"""Loader for the vendored github-linguist classification profile.

The profile answers two questions the rest of this tool could not previously
answer at all: "what language is a ``.tld`` file?" and "is this path
third-party?". It is used to **classify and rank** findings and never to filter
them -- linguist, ``scc`` and ``include_globs`` share one failure mode, which is
that each silently omits what it does not recognise, and only a walk that
reports the unknown can find the unknown.

No YAML dependency lives here. ``profiles/linguist.json`` is a derived snapshot
regenerated by hand with ``scripts/refresh_linguist.py``, which is the only
place ``pyyaml`` is imported.

Two case rules, each implemented in exactly one function so that no call site
can repeat the mistake:

* **Extensions casefold.** ``languages.py:105`` stores ``ext.lower()`` and
  ``languages.py:117`` looks up ``path.suffix.lower()``, so a comparison on the
  raw extension would report a language verdict the indexer would never have
  reached. ``.lower()`` is used rather than ``str.casefold()`` precisely because
  it is what the gate being modelled uses, and the vendored keys are written the
  same way.
* **Filenames do not.** That is linguist's own semantics and git's:
  ``Jenkinsfile`` is Groovy and ``jenkinsfile`` is nothing.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel

DEFAULT_PROFILE_PATH = Path(__file__).resolve().parent / "profiles" / "linguist.json"


class LinguistLanguage(BaseModel):
    """One language linguist claims for an extension or filename."""

    name: str
    # "programming" | "markup" | "data" | "prose". Nullable for schema
    # tolerance only: no language in the pinned snapshot omits it, so the None
    # branch is unreachable from the vendored data. Both fields are still
    # *required* to be present -- a profile that dropped a key should fail
    # validation loudly, since catching a half-succeeded refresh is the whole
    # point of this module having a test.
    type: str | None
    group: str | None


class LinguistProfile(BaseModel):
    schema_version: int
    attribution: str
    upstream_commit: str
    fetched_at: str
    # Languages in upstream languages.yml at ``upstream_commit``. Larger than
    # the number of distinct names in the two maps below, because a language
    # reachable by neither extension nor filename -- a REPL transcript, an
    # interpreter-only shell dialect -- prunes away entirely.
    upstream_language_count: int
    extensions: dict[str, list[LinguistLanguage]]
    filenames: dict[str, list[LinguistLanguage]]
    vendor_filename_patterns: list[str]
    vendor_directory_patterns: list[str]


def load_linguist_profile(path: Path | None = None) -> LinguistProfile:
    """Load and validate the vendored profile.

    Defaults to the packaged copy, mirroring how ``cli.py:1727-1729`` loads
    ``profiles/extractors.json``.
    """
    profile_path = path if path is not None else DEFAULT_PROFILE_PATH

    if not profile_path.exists():
        raise FileNotFoundError(
            f"Linguist profile file not found: {profile_path}. "
            "Ensure profiles/linguist.json exists in the package, or "
            "regenerate it with scripts/refresh_linguist.py."
        )

    with profile_path.open("r", encoding="utf-8") as handle:
        data: dict[str, Any] = json.load(handle)

    return LinguistProfile.model_validate(data)


def classify_extension(profile: LinguistProfile, ext: str) -> list[LinguistLanguage]:
    """Languages linguist claims for ``ext``, which carries a leading dot.

    Returns an empty list when linguist knows nothing about the extension --
    which is the answer for ``.tld``, ``.dtd``, ``.vm`` and ``.mf``, and is as
    load-bearing as any positive resolution.
    """
    if not ext:
        return []
    return profile.extensions.get(ext.lower(), [])


def classify_filename(profile: LinguistProfile, name: str) -> list[LinguistLanguage]:
    """Languages linguist claims for the exact filename ``name``.

    Deliberately case-sensitive; see the module docstring.
    """
    if not name:
        return []
    return profile.filenames.get(name, [])


def tree_sitter_grammar_for(ext: str) -> str | None:
    """The tree-sitter grammar registered for ``ext``, or None.

    ``ext`` carries a leading dot, and this function strips it. That is the
    whole reason the call is wrapped:
    ``tree_sitter_language_pack.detect_language_from_extension`` wants the
    extension *without* the dot -- ``("dtd")`` returns ``"dtd"`` while
    ``(".dtd")`` returns ``None`` -- so a call site that passes the dotted form
    empties the grammar column with no error at all.

    The answer means "a grammar is registered for this extension", never "this
    content could be parsed": ``.xmi`` is XML to linguist, an XML grammar
    exists, and nothing claims that extension. That keeps such a row a triage
    decision rather than a silently-answered question.
    """
    if not ext:
        return None

    from tree_sitter_language_pack import detect_language_from_extension  # type: ignore

    return detect_language_from_extension(ext.lower().lstrip("."))
